language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.3
    - android-23

script: "./gradlew build"

    # Support library
    - extra-android-support
    - extra-android-m2repository